from tkinter import *
import sqlite3
root=Tk()
root.geometry('600x500')
bg=PhotoImage(file="\\Users\hp\\OneDrive\\Documents\\Office\\Works\\my new work\\Images\\Webber.png")
#show image using Label
label1=Label(root,image=bg)
label1.place(x=0,y=0)
root.title("Registration Form")
Fullname=StringVar()
Email=StringVar()
Var=IntVar()
C=StringVar()
Var1=IntVar()
def database():
    name1=Fullname.get()
    email=Email.get()
    gender=Var.get()
    country=C.get()
    Prog=Var1.get()
    conn=sqlite3.connect('Form.db')
    with conn:
        cursor=conn.cursor()
        cursor.execute("""CREATE TABLE IF NOT EXISTS Student(Fullname TEXT,Email TEXT,Gender TEXT,Country TEXT,Programming TEXT)""");
        cursor.execute('INSERT INTO Student(Fullname,Email,Gender,Country,Programming)VALUES(?,?,?,?,?)',(name1,email,gender,country,Prog))
        conn.commit()
label_0=Label(root,text="Registration Form",width=20,font=('bold',10))
label_0.place(x=90,y=53)
label_1=Label(root,text="Full Name",width=10,font=('bold',10))
label_1.place(x=80,y=130)        
entry_1=Entry(root,textvar=Fullname)
entry_1.place(x=240,y=130)
label_2=Label(root,text="Email",width=10,font=('bold',10))
label_2.place(x=68,y=180)
entry_2=Entry(root,textvar=Email)
entry_2.place(x=240,y=180)
label_3=Label(root,text="Gender",width=10,font=('bold',10))
label_3.place(x=70,y=230)
Radiobutton(root,text="Male",padx=5,variable=Var,value=1).place(x=235,y=230)
Radiobutton(root,text="Female",padx=10,variable=Var,value=2).place(x=290,y=230)
label_4=Label(root,text="Country",width=10,font=('bold',10))
label_4.place(x=70,y=280)
list1=['Nigeria','Ghana','South Africa','Japan','Kenya'];
droplist=OptionMenu(root,C,*list1)
droplist.config(width=15)
C.set("Select Your Country")
droplist.place(x=240,y=280)
label_5=Label(root,text="Programming Language",width=20,font=('bold',10))
label_5.place(x=85,y=330)
Var2=IntVar()
Checkbutton(root,text="Java",variable=Var1).place(x=235,y=330)
Checkbutton(root,text="Python",variable=Var2).place(x=290,y=330)
Button(root,text="Submit",width=10,bg="brown",fg="White",command=database).place(x=180,y=380)
root.mainloop()
